services:
  tracker:
    image: ghcr.io/hostmaster/crypto-wallet-tracker:latest
    platform: linux/x86_64
    build:
      context: .
      target: runtime
      args:
        - PYTHON_VERSION=3.11
    volumes:
      - db-data:/data
    secrets:
      - etherscan_api_key
      - tg_bot_token
      - tg_chat_id
      - wallet_address

secrets:
  etherscan_api_key:
    file: ./etherscan_api_key.txt
  tg_bot_token:
    file: ./tg_bot_token.txt
  tg_chat_id:
    file: ./tg_chat_id.txt
  wallet_address:
    file: ./wallet_address.txt

volumes:
  db-data:
